name: generate animation

on: 
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: LeehXD
        id: https://raw.githubusercontent.com/leoyassuda/leoyassuda/0f4f7c03bc44e22e647a4076d8012b52afb642e0/github-contribution-grid-snake.svg
        with:
          github_user_name: LeehXD
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_ANIMATION_PROFILE }}.
